### ISSUE TITLE
urlsnarf not displaying url activity

### ISSUE THREAD

**Issue by eric-ooi** [hak5/nano-tetra-modules#82]
I just installed urlsnarf with dependencies on a factory-reset Pineapple Tetra running 2.6.1.  When I run urlsnarf from either the GUI or command line, it will start but never shows any log output despite browsing to HTTP websites.  Sniffing the same interface with tcpdump does show traffic following through.

**Comment by bibi1959** [comment]
i am facing the same problem after update. It seems update is not working - at least is not working as it was before. ity as it has been my best module. I hope  it will be solved
